Repository Career-HY/Career-HY-Service, pull requests merged in 2025-05, with the labels that each got.

#9 [FIX] gitignore 버그 수정
  .env
  ingestion/.env
Labels: 🐞 BugFix

#12 [SETTING] 백엔드 개발환경 세팅
  .DS_Store
  backend/Dockerfile
  backend/imsi.txt
  backend/requirements.txt
  backend/src/__pycache__/backend.cpython-312.pyc
  backend/src/backend.py
  backend/src/config/config.py
  backend/src/db.py
  docker-compose.yml
  ingestion/src/config/ingestion.yml
Labels: ⚙ Setting

#14 [FEAT] 회원가입, 로그인 구현
  backend/src/api/__init__.py
  backend/src/api/routers/user.py
  backend/src/backend.py
  backend/src/crud/user.py
  backend/src/db/models.py
  backend/src/db/session.py
  backend/src/schemas/user.py
  docker-compose.yml
  shared/imsi.txt
Labels: ✨ Feature, Backend

#18 [BACKEND/REFACTOR] 쿠키 기반 세션 로그인
  backend/requirements.txt
  backend/src/api/routers/user.py
  backend/src/backend.py
  backend/src/config/config.py
  backend/src/util/deps.py
Labels: 🔨 Refactor, Backend

#20 [INGESTION/SETTING] ingestion 서버 fast api 설정
  docker-compose.yml
  ingestion/Dockerfile
  ingestion/requirements.txt
  ingestion/src/ingestion.py
Labels: ⚙ Setting, Ingestion

#26 [FEAT] 채팅방 관련 API 작업
  .gitignore
  backend/src/api/routers/chatroom.py
  backend/src/backend.py
  backend/src/crud/chatroom.py
  backend/src/db/models.py
  backend/src/schemas/chatroom.py
Labels: ✨ Feature, Backend

#32 [TEST] 백엔드 배포 테스트
  .github/workflows/deploy-ingestion.yml
  backend/src/backend.py
Labels: ⚙ Setting

#33 Setting/#31/backend deploy test
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-ingestion.yml
Labels: ⚙ Setting

#35 [TEST] 백엔드 배포 테스트
  backend/src/backend.py
Labels: ✅ Test

#38 [FEAT] 문서 검색 api 구현
  .gitignore
  ingestion/check_chroma.py
  ingestion/requirements.txt
  ingestion/src/__init__.py
  ingestion/src/__pycache__/chunker.cpython-312.pyc
  ingestion/src/__pycache__/cleaner.cpython-312.pyc
  ingestion/src/__pycache__/embedder.cpython-312.pyc
  ingestion/src/__pycache__/extractor.cpython-312.pyc
  ingestion/src/__pycache__/loader.cpython-312.pyc
  ingestion/src/__pycache__/tokencounter.cpython-312.pyc
  ingestion/src/__pycache__/vector.cpython-312.pyc
  ingestion/src/api/__init__.py
  ingestion/src/api/models.py
  ingestion/src/api/retrieval.py
  ingestion/src/check_chroma.py
  ingestion/src/ingestion.py
  ingestion/src/logger.py
  ingestion/src/util/logging.py
  ingestion/src/vector.py
Labels: ✨ Feature, Ingestion

#41 [SETTING] LLM 출력 서버 개발 환경 세팅
  .github/workflows/deploy-llm-service.yml
  docker-compose.yml
  llm-service/Dockerfile
  llm-service/imsi.txt
  llm-service/requirements.txt
  llm-service/src/config/config.py
  llm-service/src/llm_service.py
Labels: ⚙ Setting, LLM-Service

#43 [TEST] 검색 서버, llm 서버 배포 테스트
  ingestion/src/api/retrieval.py
  ingestion/src/ingestion.py
  llm-service/src/llm_service.py
Labels: ✅ Test

#45 [Test] 배포 테스트
  backend/src/backend.py
  ingestion/src/ingestion.py
  llm-service/src/llm_service.py
Labels: ✅ Test

#47 [TEST] 배포 테스트
  backend/src/backend.py
  ingestion/src/ingestion.py
  llm-service/src/llm_service.py
Labels: ✅ Test

#49 [TEST] 검색 서버 배포 테스트
  ingestion/src/ingestion.py
Labels: ✅ Test

#53 [TEST] 통합 배포 테스트 마지막 ...
  backend/src/backend.py
  ingestion/src/ingestion.py
  llm-service/.DS_Store
  llm-service/src/llm_service.py
Labels: ✅ Test
